#!/bin/bash
set -euo pipefail

DOCKER_PRUNE_UNTIL=${DOCKER_PRUNE_UNTIL:-4h}

## ------------------------------------------
## Prune stuff that doesn't affect cache hits

docker network prune -af --filter "until=${DOCKER_PRUNE_UNTIL}"
docker container prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL}"
docker volume prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL}"