#!/bin/bash
set -euo pipefail

exec > /var/log/elastic-stack.log 2>&1 # Logs to elastic-stack.log

DOCKER_PRUNE_UNTIL=${DOCKER_PRUNE_UNTIL:-1h}

mark_instance_unhealthy() {
  # cancel any running buildkite builds
  killall -QUIT buildkite-agent || true

  # mark the instance for termination
  aws autoscaling set-instance-health \
    --instance-id "$(curl http://169.254.169.254/latest/meta-data/instance-id)" \
    --health-status Unhealthy
}

trap mark_instance_unhealthy ERR

## -----------------------------------------------------------------
## Check disk, we only want to prune images/containers if we have to

if ! /usr/local/bin/bk-check-disk-space.sh ; then
  echo "Cleaning up docker resources older than ${DOCKER_PRUNE_UNTIL}"
  docker image prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL}"

  if ! check_disk_healthy ; then
    echo "Disk health checks failed" >&2
    exit 1
  fi
fi
