#!/bin/bash
set -euo pipefail

if [[ $EUID -eq 0 ]]; then
  exec >> /var/log/elastic-stack.log 2>&1 # Logs to elastic-stack.log
fi

mark_instance_unhealthy() {
  # cancel any running buildkite builds
  killall -QUIT buildkite-agent || true

  # mark the instance for termination
  aws autoscaling set-instance-health \
    --instance-id "$(curl http://169.254.169.254/latest/meta-data/instance-id)" \
    --health-status Unhealthy
}

trap mark_instance_unhealthy ERR

# Load config from file if it exists
if [[ -f /var/lib/buildkite-agent/cron-env ]] ; then
  # shellcheck source=/dev/null
  source /var/lib/buildkite-agent/cron-env
else
  DISK_MIN_AVAILABLE=5G
fi

## -----------------------------------------------------------------
## Check disk, we only want to prune images/containers if we have to

if ! /usr/local/bin/bk-check-disk-space.sh "$DISK_MIN_AVAILABLE" ; then
  echo "Cleaning up docker resources older than 1h"
  docker image prune --all --force --filter "until=1h"

  if ! /usr/local/bin/bk-check-disk-space.sh "$DISK_MIN_AVAILABLE" ; then
    echo "Disk health checks failed" >&2
    exit 1
  fi
fi
