#!/bin/bash
set -euo pipefail

if [[ $EUID -eq 0 ]]; then
  exec >> /var/log/elastic-stack.log 2>&1 # Logs to elastic-stack.log
fi

# Load config from file if it exists
if [[ -f /var/lib/buildkite-agent/cron-env ]] ; then
  # shellcheck source=/dev/null
  source /var/lib/buildkite-agent/cron-env
else
  DOCKER_PRUNE_UNTIL=4h
fi

## ------------------------------------------
## Prune stuff that doesn't affect cache hits

docker network prune --force --filter "until=${!DOCKER_PRUNE_UNTIL}"
docker container prune --force --filter "until=${!DOCKER_PRUNE_UNTIL}"
