#!/bin/bash
set -euo pipefail

if [[ $EUID -eq 0 ]]; then
  exec >> /var/log/elastic-stack.log 2>&1 # Logs to elastic-stack.log
fi

DOCKER_PRUNE_UNTIL=${DOCKER_PRUNE_UNTIL:-1h}

mark_instance_unhealthy() {
  # cancel any running buildkite builds
  killall -QUIT buildkite-agent || true

  # mark the instance for termination
  echo "Marking instance as unhealthy"

  TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
  aws autoscaling set-instance-health \
    --instance-id "$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)" \
    --health-status Unhealthy
}

trap mark_instance_unhealthy ERR

## -----------------------------------------------------------------
## Check disk, we only want to prune images/containers/build caches
## if we really need to

if ! /usr/local/bin/bk-check-disk-space.sh ; then
  echo "Cleaning up docker resources older than ${DOCKER_PRUNE_UNTIL}"
  docker image prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL}"
  docker builder prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL}"

  if ! /usr/local/bin/bk-check-disk-space.sh ; then
    echo "Disk health checks failed" >&2
    exit 1
  fi
fi
