#!/bin/bash -eux

cd $(dirname $0)
scripts/configure-host.sh
scripts/install-docker.sh

# Periodic garbage-collection of Docker images
curl https://raw.githubusercontent.com/spotify/docker-gc/master/docker-gc > /usr/local/bin/docker-gc
chmod +x /usr/local/bin/docker-gc
ln -s /usr/local/bin/docker-gc /etc/cron.weekly

# Start docker agent
docker run -dt --name=buildkite-agent \
  -e BUILDKITE_AGENT_TOKEN="$BUILDKITE_AGENT_TOKEN" \
  -e BUILDKITE_AGENT_META_DATA="elastic=true,queue=elastic,docker=true,ci=true" \
  -e BUILDKITE_AGENT_NAME="buildkite-%n" \
  -v /usr/bin/docker:/usr/bin/docker \
  -v /root/provision/id_rsa_buildkite:/root/.ssh/id_rsa \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /opt/buildkite-cache:/opt/buildkite-cache \
  --restart=always \
  buildkite/agent:ubuntu