#!/bin/bash

set -eu -o pipefail

echo "stopping buildkite-agent gracefully"

/etc/init.d/buildkite-agent stop

while [[ $(/etc/init.d/buildkite-agent status) == "Running" ]]; do
  sleep 0.5
done

echo "buildkite-agent stopped"
