#!/bin/bash

# Files that are created by Docker containers end up with strange user and
# group ids, usually 0 (root). Docker namespacing will one day save us, but it
# can only map a single docker user id to a given user id (not any docker user
# id to a single system user id).
#
# Until we can map any old user id back to
# buildkite-agent automatically with Docker, then we just need to fix the
# permissions manually before each build runs so git clean can work as
# expected.

set -eu -o pipefail

# We need to scope this to only the currently running agent's builds, but we
# also need to control security and make sure arbitrary folders can't be
# chmoded.
#
# We prepare the agent build directory basename in the environment hook and
# pass it as the first argument. In here we just need to check that it contains
# no slashes and isn't a traversal component.
AGENT_BUILDS_NAME="$1"
# => "my-agent-1"

# Make sure it doesn't contain any slashes by substituting slashes with nothing
# and making sure it doesn't change
if [[ "${AGENT_BUILDS_NAME//\//}" != "${AGENT_BUILDS_NAME}" ]]; then
	exit 1
fi

# Now we know this name has only non-slash characters.
#
# We just need to check that it's not "." or ".." to prevent traversal:
if [[ "${AGENT_BUILDS_NAME}" == "." || "${AGENT_BUILDS_NAME}" == ".." ]]; then
	exit 2
fi

# We also need to make sure it's not empty so we don't collide with other agents:
if [[ -z "${AGENT_BUILDS_NAME}" ]]; then
	exit 3
fi

# We know the builds path:
BUILDS_PATH="/var/lib/buildkite-agent/builds"

# And now we can reconstruct the full agent builds path:
AGENT_BUILDS_PATH="${BUILDS_PATH}/${AGENT_BUILDS_NAME}"
# => "/var/lib/buildkite-agent/builds/my-agent-1"

if [[ -e "${AGENT_BUILDS_PATH}" ]]; then
	/bin/chmod -R buildkite-agent:buildkite-agent "${AGENT_BUILDS_PATH}"
fi

# Manual tests (anybody know a good way to test this?):
#
# ./fix-buildkite-agent-builds-permissions "/"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "one/"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "/two"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "one/two"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "one/two/three"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "/two/"
# => exit 1
#
# ./fix-buildkite-agent-builds-permissions "."
# => exit 2
#
# ./fix-buildkite-agent-builds-permissions ".."
# => exit 2
#
# ./fix-buildkite-agent-builds-permissions ""
# => exit 3
