#!/bin/bash

set -euo pipefail

instance_id=$(curl -fsSL http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl -fsSL http://169.254.169.254/latest/meta-data/placement/availability-zone | head -c -1)

aws autoscaling set-instance-health --instance-id "$instance_id" --region "$region" --health-status "Unhealthy"
