#!/bin/bash
set -eu -o pipefail

# Import BUILDKITE_AGENTS_PER_INSTANCE
eval "$(cat /var/lib/buildkite-agent/cfn-env)"

echo "Stopping buildkite-agent gracefully"
systemctl stop "buildkite-agent@*"

# Need to ensure it's the buildkite-agent user, so it doesn't match this lifecycled handler script
while pgrep -u buildkite-agent buildkite-agent > /dev/null; do
  echo "Waiting for all buildkite-agent processes to have stopped..."
  sleep 5
done

echo "All buildkite-agent processes have stopped"
