[Unit]
FailureAction=poweroff-force

[Service]
Type=notify
NotifyAccess=main
WatchdogSec=3min
WatchdogSignal=SIGKILL
TimeoutAbortSec=10s
TimeoutStartSec=infinity
TimeoutStopSec=10s
ExecStopPost=
Restart=no
OOMScoreAdjust=0
OOMPolicy=kill
