#!/bin/bash

set -eu -o pipefail

export COMPOSE_FILE=/var/lib/buildkite-agent/docker-compose.yml

cd /var/lib/buildkite-agent
docker-compose stop agent

while test -n "$(docker-compose ps -q)" ; do
  echo "Waiting for all buildkite-agent containers to have stopped..."
  sleep 5
done

echo "All buildkite-agent containers have stopped"
