env:
  AWS_STACK_NAME: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
  AWS_STACK_QUEUE_NAME: "testqueue-${BUILDKITE_BUILD_NUMBER}"

steps:
  - name: ":bash: Lint"
    command: .buildkite/steps/lint.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - name: ":bash: Unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v2.1.0:
        run: unit-tests
        config: docker-compose.unit-tests.yml

  - wait
  - name: ":packer: Build"
    command: .buildkite/steps/packer.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - wait
  - name: ":cloudformation: Launch"
    command: .buildkite/steps/test.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"

  - wait
  - name: ":buildkite: Bats Tests"
    command: "/usr/local/bin/bats tests/"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-${BUILDKITE_BUILD_NUMBER}"

  - name: ":buildkite: Server Specs"
    command: "goss validate"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-${BUILDKITE_BUILD_NUMBER}"

  - wait
  - name: ":cloudformation: 🚚 🌎"
    command: .buildkite/steps/copy.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/mappings.yml"

  - wait
  - name: ":cloudformation: :rocket:"
    command: .buildkite/steps/publish.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    concurrency_group: "aws-stack-publish"
    concurrency: 1
    artifact_paths: "build/*.yml"

  - wait
  - name: "Cleanup"
    command: .buildkite/steps/cleanup.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
