steps:
  - name: ":broom: Delete AMIs ({{matrix}})"
    command: .buildkite/steps/clean-old-amis
    agents:
      queue: "oss-deploy"
    env:
      # DRY_RUN: true
      AWS_REGION: "{{matrix}}"
    # list of regions should match .buildkite/steps/copy.sh
    matrix:
      - "us-east-1"
      - "us-east-2"
      - "us-west-1"
      - "us-west-2"
      - "af-south-1"
      - "ap-east-1"
      - "ap-south-1"
      - "ap-northeast-2"
      - "ap-northeast-1"
      - "ap-southeast-2"
      - "ap-southeast-1"
      - "ca-central-1"
      - "eu-central-1"
      - "eu-west-1"
      - "eu-west-2"
      - "eu-south-1"
      - "eu-west-3"
      - "eu-north-1"
      - "me-south-1"
      - "sa-east-1"
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-elastic-stack-for-aws-ami-cleaner
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - branch_build
      - docker-compose#v5.10.0:
          run: ruby
          config: .buildkite/docker-compose.yml
          propagate-aws-auth-tokens: true
