#!/bin/bash

set -eu -o pipefail

if [[ "${DOCKER_PRUNE_ON:-emergency}" == "post-job" ]]; then
  echo "~~~ :docker: Cleaning up old docker resources"
  docker image prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL:-4h}" || true
  docker builder prune --all --force --filter "until=${DOCKER_PRUNE_UNTIL:-4h}" || true
fi

# clean up our temporary docker config
if [[ -n "${BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY:-}" && -d "$BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY" ]]; then
  rm -rf "$BUILDKITE_DOCKER_CONFIG_TEMP_DIRECTORY"
fi

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" && "${SECRETS_PLUGIN_ENABLED:-}" == "1" ]]; then
  export BUILDKITE_PLUGIN_S3_SECRETS_BUCKET="$BUILDKITE_SECRETS_BUCKET"

  # shellcheck source=/dev/null
  source /usr/local/buildkite-aws-stack/plugins/secrets/hooks/pre-exit
fi
