
Resources:
  AgentScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseAutoscaling
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown: 300
      ScalingAdjustment : $(ScaleUpAdjustment)

  AgentScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Condition: UseAutoscaling
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown: 300
      ScalingAdjustment: $(ScaleDownAdjustment)

  AgentUtilizationAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Condition: UseAutoscaling
   Properties:
      AlarmDescription: Scale-up if ScheduledJobs > 0 for 1 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ $(AgentScaleUpPolicy) ]
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: GreaterThanThreshold

  AgentUtilizationAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Condition: UseAutoscaling
   Properties:
      AlarmDescription: Scale-down if UnfinishedJobs == 0 for N minutes
      MetricName: UnfinishedJobsCount
      Namespace: Buildkite
      Statistic: Maximum
      Period: $(ScaleDownPeriod)
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ $(AgentScaleDownPolicy) ]
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: LessThanOrEqualToThreshold
