
Resources:
  MissingMetricsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: SampleCount
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: LessThanOrEqualToThreshold

  AgentScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown: 120
      ScalingAdjustment : $(ScaleUpAdjustment)

  AgentScaleDownPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: $(AgentAutoScaleGroup)
      Cooldown : 60
      ScalingAdjustment: $(ScaleDownAdjustment)

  AgentUtilizationAlarmHigh:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-up if ScheduledJobs > 0 for 1 minute
      MetricName: ScheduledJobsCount
      Namespace: Buildkite
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ $(AgentScaleUpPolicy) ]
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: GreaterThanThreshold

  AgentUtilizationAlarmLow:
   Type: AWS::CloudWatch::Alarm
   Properties:
      AlarmDescription: Scale-down if UnfinishedJobs == 0 for 15 minutes
      MetricName: UnfinishedJobsCount
      Namespace: Buildkite
      Statistic: Maximum
      Period: 900
      EvaluationPeriods: 1
      Threshold: 0
      AlarmActions: [ $(AgentScaleDownPolicy) ]
      Dimensions:
        - Name: Queue
          Value: $(BuildkiteQueue)
      ComparisonOperator: LessThanOrEqualToThreshold
