
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Condition: CreateMetricsStack
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"

  LambdaExecutionPolicy:
    DependsOn: LambdaExecutionRole
    Type: AWS::IAM::Policy
    Condition: CreateMetricsStack
    Properties:
      PolicyName: AccessToCloudwatchForBuildkiteMetrics
      Roles:
      - { Ref: LambdaExecutionRole }
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          - cloudwatch:PutMetricData
          Resource:
          - "*"

  BuildkiteMetricsFunction:
    Type: AWS::Lambda::Function
    DependsOn:
    - LambdaExecutionRole
    - LambdaExecutionPolicy
    Condition: CreateMetricsStack
    Properties:
      Code:
        S3Bucket: { 'Fn::FindInMap': [MetricsLambdaBucket, { Ref: 'AWS::Region' }, 'Bucket'] }
        S3Key: "buildkite-metrics-v3.0.0-lambda.zip"
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Timeout: 120
      Handler: handler.handle
      Runtime: python2.7
      MemorySize: 128
      Environment:
        Variables:
          BUILDKITE_AGENT_TOKEN: { Ref: BuildkiteAgentToken }
          BUILDKITE_QUEUE: { Ref: BuildkiteQueue }
          AWS_STACK_ID: { Ref: "AWS::StackId" }
          AWS_STACK_NAME: { Ref: "AWS::StackName" }
          AWS_ACCOUNT_ID: { Ref: "AWS::AccountId" }

  ScheduledRule:
    Type: "AWS::Events::Rule"
    Condition: CreateMetricsStack
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 minute)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "BuildkiteMetricsFunction"
              - "Arn"
          Id: "TargetBuildkiteMetricsFunction"

  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Condition: CreateMetricsStack
    Properties:
      FunctionName: { Ref: BuildkiteMetricsFunction }
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
