#!/bin/bash

if [[ -n "${SSH_AGENT_PID:-}" ]] && ps -p "$SSH_AGENT_PID" &>/dev/null; then
  echo "~~~ Stopping ssh-agent ${SSH_AGENT_PID}"
  ssh-agent -k
fi

if [[ -n "${GIT_CREDENTIALS_FILE:-}" ]] ; then
  echo "~~~ Cleaning up git credentials"
  rm "$GIT_CREDENTIALS_FILE"
fi