#!/bin/bash
set -eu -o pipefail

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../../../" && pwd )"

if [[ -n "${AWS_ECR_LOGIN:-}" && "${ECR_PLUGIN_ENABLED:-true}" =~ (on|1|true) ]] ; then
  export BUILDKITE_PLUGIN_ECR_LOGIN=1

  # shellcheck source=/dev/null
  source "$BASEDIR/plugins/ecr/hooks/pre-command"
fi

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" && "${SECRETS_PLUGIN_ENABLED:-true}"  =~ (on|1|true) ]] ; then
  export BUILDKITE_PLUGIN_S3_SECRETS_BUCKET="$BUILDKITE_SECRETS_BUCKET"

  # shellcheck source=/dev/null
  source $BASEDIR/plugins/secrets/hooks/pre-command
fi

if [[ -n "${DOCKER_LOGIN_USER:-}" && "${DOCKER_LOGIN_PLUGIN_ENABLED:-true}" =~ (on|1|true) ]] ; then
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME="$DOCKER_LOGIN_USER"
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_PASSWORD="$DOCKER_LOGIN_PASSWORD"
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_SERVER="${DOCKER_LOGIN_SERVER:-}"

  # shellcheck source=/dev/null
  source /usr/local/buildkite-aws-stack/plugins/docker-login/hooks/pre-command
fi
