#!/bin/bash

set -eu -o pipefail

if [[ "${BUILDKITE_ECR_POLICY:-}" != "none" && "${ECR_PLUGIN_ENABLED:-}" == "1" ]] ; then
  # shellcheck source=/dev/null
  source /usr/local/buildkite-aws-stack/plugins/ecr/hooks/pre-command
fi

if [[ -n "${DOCKER_LOGIN_USER:-}" && "${DOCKER_LOGIN_PLUGIN_ENABLED:-}" == "1" ]] ; then
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_USERNAME="$DOCKER_LOGIN_USER"
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_PASSWORD="$DOCKER_LOGIN_PASSWORD"
  export BUILDKITE_PLUGIN_DOCKER_LOGIN_SERVER="${DOCKER_LOGIN_SERVER:-}"

  # shellcheck source=/dev/null
  source /usr/local/buildkite-aws-stack/plugins/docker-login/hooks/pre-command
fi
