#!/bin/bash
set -eu

echo '+++ :house_with_garden: Setting up the environment'

[[ -f ~/.docker/config.json ]] && rm ~/.docker/config.json
[[ -f ~/.dockercfg ]] && rm ~/.dockercfg

 # handle docker hub authentication
if [[ -n "${DOCKER_HUB_AUTH:-}" ]] ; then
  echo "DOCKER_HUB_AUTH is no longer supported, use DOCKER_HUB_USER, DOCKER_HUB_PASSWORD and DOCKER_HUB_EMAIL."
  exit 1
elif [[ -n "${DOCKER_HUB_USER:-}" && -n "${DOCKER_HUB_PASSWORD:-}" && -n "${DOCKER_HUB_EMAIL:-}" ]] ; then
  echo "~~~ Authenticating with docker hub as ${DOCKER_HUB_USER}"
  docker login --username="${DOCKER_HUB_USER}" --password="${DOCKER_HUB_PASSWORD}" --email="${DOCKER_HUB_EMAIL}"
elif [[ -n "${DOCKER_HUB_USER:-}" && -n "${DOCKER_HUB_PASSWORD:-}" ]] ; then
  echo "Missing DOCKER_HUB_EMAIL."
  exit 1
fi

eval `ssh-agent -s`

# startup an ssh-agent with the ssh-key
if [[ -n "${SSH_KEY_URL:-}" ]] ; then
  echo "~~~ Downloading github ssh key"
  TMPKEY=$(mktemp /tmp/buildkite.XXXXXXXXXX)
  trap "rm $TMPKEY" exit
  env -i aws s3 cp ${SSH_KEY_URL:-} $TMPKEY
  ssh-add $TMPKEY
fi

if [[ $(docker ps -q | wc -l) -gt 0 ]] ; then
  echo "~~~ Stopping existing docker containers"
  docker stop $(docker ps -q)
fi