#!/bin/bash
set -eu

echo '+++ :house_with_garden: Setting up the environment'

source ~/cfn-env

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] && [[ -z "${BUILDKITE_SECRETS_KEY:-}" ]] ; then
  echo "A SecretsBucket was provided, but no encryption key via BUILDKITE_SECRETS_KEY."
  exit 1
fi

eval "$(ssh-agent -s)"

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] ; then
  [[ -d ~/secrets ]] || mkdir -p ~/secrets

  echo "+++ Downloading secrets from $BUILDKITE_SECRETS_BUCKET"
  env -i aws s3 sync --delete --sse-c AES256 --sse-c-key "${BUILDKITE_SECRETS_KEY}" "s3://${BUILDKITE_SECRETS_BUCKET}" ~/secrets/

  ssh_key_file="$HOME/secrets/${SSH_KEY_NAME:-id_rsa_github}"
  [[ -f $ssh_key_file ]] && ssh-add "$ssh_key_file"

  env_file="$HOME/secrets/env"
  [[ -f $env_file ]] && eval "$(cat "$env_file")"
fi

if [[ $(docker ps -q | wc -l) -gt 0 ]] ; then
  echo "~~~ Stopping existing :docker: containers"
  docker stop $(docker ps -q)
fi