#!/bin/bash
set -eu

s3_exists() {
  env -i aws s3 ls "${BUILDKITE_SECRETS_BUCKET}/$1" "$2" &>/dev/null
}

s3_download() {
  env -i aws s3 cp --quiet --sse-c AES256 --sse-c-key "${BUILDKITE_SECRETS_KEY}" "${BUILDKITE_SECRETS_BUCKET}/$1" /dev/stdout
}

echo '+++ :house_with_garden: Setting up the environment'

source ~/cfn-env

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] && [[ -z "${BUILDKITE_SECRETS_KEY:-}" ]] ; then
  echo "A SecretsBucket was provided, but no encryption key via BUILDKITE_SECRETS_KEY."
  exit 1
fi

eval "$(ssh-agent -s)"

if [[ -n "${BUILDKITE_SECRETS_BUCKET:-}" ]] ; then

  echo "Downloading ssh key from $BUILDKITE_SECRETS_BUCKET"
  ssh-add <(s3_download "${SSH_KEY_NAME:-id_rsa_github}")

  if s3_exists "env" ; then
     echo "Downloading env from $BUILDKITE_SECRETS_BUCKET"
    eval "$(s3_download env)"
  fi
fi

if [[ $(docker ps -q | wc -l) -gt 0 ]] ; then
  echo "~~~ Stopping existing :docker: containers"
  docker stop $(docker ps -q)
fi