#!/bin/bash
set -eu

[[ -f ~/.docker/config.json ]] && rm ~/.docker/config.json
[[ -f ~/.dockercfg ]] && rm ~/.dockercfg

if [[ -n "${DOCKER_AUTH:-}" ]] ; then
  DOCKER_HUB_AUTH=$DOCKER_AUTH
  QUAY_AUTH=$DOCKER_AUTH
  unset DOCKER_AUTH
fi

if [[ -n "${DOCKER_HUB_AUTH:-}" ]] ; then
  DOCKER_HUB_USER=$(jq -r '."https://index.docker.io/v1/".auth' <<< "$DOCKER_HUB_AUTH" | base64 --decode | cut -d: -f1)
  DOCKER_HUB_PASSWORD=$(jq -r '."https://index.docker.io/v1/".auth' <<< "$DOCKER_HUB_AUTH" | base64 --decode | cut -d: -f2)
  unset DOCKER_HUB_AUTH
fi

if [[ -n "${DOCKER_HUB_USER:-}" && -n "${DOCKER_HUB_PASSWORD:-}" ]] ; then
  echo "~~~ Authenticating with :docker: hub as ${DOCKER_HUB_USER}"
  docker login --username="${DOCKER_HUB_USER}" --password="${DOCKER_HUB_PASSWORD}"
fi

unset DOCKER_HUB_USER
unset DOCKER_HUB_PASSWORD

if [[ -n "${QUAY_AUTH:-}" ]] ; then
  QUAY_USER=$(jq -r '."quay.io".auth' <<< "$QUAY_AUTH" | base64 --decode | cut -d: -f1)
  QUAY_PASSWORD=$(jq -r '."quay.io".auth' <<< "$QUAY_AUTH" | base64 --decode | cut -d: -f2)
  unset QUAY_AUTH
fi

if [[ -n "${QUAY_USER:-}" && -n "${QUAY_PASSWORD:-}" ]] ; then
  echo "~~~ Authenticating with quay.io hub as ${QUAY_USER}"
  docker login --username="${QUAY_USER}" --password="${QUAY_PASSWORD}" quay.io
fi

unset QUAY_USER
unset QUAY_PASSWORD
